/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SwimLane {
        "laneTitle": string;
        "statusId": number;
        "tasks": any;
    }
    interface SwimLaneTask {
        "task": any;
    }
    interface SwimLanes {
        "config": any;
    }
}
declare global {
    interface HTMLSwimLaneElement extends Components.SwimLane, HTMLStencilElement {
    }
    var HTMLSwimLaneElement: {
        prototype: HTMLSwimLaneElement;
        new (): HTMLSwimLaneElement;
    };
    interface HTMLSwimLaneTaskElement extends Components.SwimLaneTask, HTMLStencilElement {
    }
    var HTMLSwimLaneTaskElement: {
        prototype: HTMLSwimLaneTaskElement;
        new (): HTMLSwimLaneTaskElement;
    };
    interface HTMLSwimLanesElement extends Components.SwimLanes, HTMLStencilElement {
    }
    var HTMLSwimLanesElement: {
        prototype: HTMLSwimLanesElement;
        new (): HTMLSwimLanesElement;
    };
    interface HTMLElementTagNameMap {
        "swim-lane": HTMLSwimLaneElement;
        "swim-lane-task": HTMLSwimLaneTaskElement;
        "swim-lanes": HTMLSwimLanesElement;
    }
}
declare namespace LocalJSX {
    interface SwimLane {
        "laneTitle"?: string;
        "statusId"?: number;
        "tasks"?: any;
    }
    interface SwimLaneTask {
        "task"?: any;
    }
    interface SwimLanes {
        "config"?: any;
    }
    interface IntrinsicElements {
        "swim-lane": SwimLane;
        "swim-lane-task": SwimLaneTask;
        "swim-lanes": SwimLanes;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "swim-lane": LocalJSX.SwimLane & JSXBase.HTMLAttributes<HTMLSwimLaneElement>;
            "swim-lane-task": LocalJSX.SwimLaneTask & JSXBase.HTMLAttributes<HTMLSwimLaneTaskElement>;
            "swim-lanes": LocalJSX.SwimLanes & JSXBase.HTMLAttributes<HTMLSwimLanesElement>;
        }
    }
}
