/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SwimLane {
        "cards": any;
        "columnId": number;
        "laneTitle": string;
        "onUpdateCardStatus": any;
        "renderCardContent": any;
    }
    interface SwimLanes {
        "config": any;
    }
}
declare global {
    interface HTMLSwimLaneElement extends Components.SwimLane, HTMLStencilElement {
    }
    var HTMLSwimLaneElement: {
        prototype: HTMLSwimLaneElement;
        new (): HTMLSwimLaneElement;
    };
    interface HTMLSwimLanesElement extends Components.SwimLanes, HTMLStencilElement {
    }
    var HTMLSwimLanesElement: {
        prototype: HTMLSwimLanesElement;
        new (): HTMLSwimLanesElement;
    };
    interface HTMLElementTagNameMap {
        "swim-lane": HTMLSwimLaneElement;
        "swim-lanes": HTMLSwimLanesElement;
    }
}
declare namespace LocalJSX {
    interface SwimLane {
        "cards"?: any;
        "columnId"?: number;
        "laneTitle"?: string;
        "onUpdateCardStatus"?: any;
        "renderCardContent"?: any;
    }
    interface SwimLanes {
        "config"?: any;
    }
    interface IntrinsicElements {
        "swim-lane": SwimLane;
        "swim-lanes": SwimLanes;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "swim-lane": LocalJSX.SwimLane & JSXBase.HTMLAttributes<HTMLSwimLaneElement>;
            "swim-lanes": LocalJSX.SwimLanes & JSXBase.HTMLAttributes<HTMLSwimLanesElement>;
        }
    }
}
